### ISSUE TITLE
windows 10 Pro x64: 6 test failures

### ISSUE THREAD

**Issue by pmq20** [enclose-io/node-compiler#5]
```
not ok 54 parallel/test-child-process-double-pipe
# events.js:160
#       throw er; // Unhandled 'error' event
#       ^
#
# Error: spawn grep ENOENT
#     at exports._errnoException (util.js:1026:11)
#     at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
#     at onErrorNT (internal/child_process.js:359:16)
#     at _combinedTickCallback (internal/process/next_tick.js:74:11)
#     at process._tickCallback (internal/process/next_tick.js:98:9)
#     at Module.runMain (module.js:674:11)
#     at run (bootstrap_node.js:389:7)
#     at startup (bootstrap_node.js:144:9)
#     at bootstrap_node.js:530:3
  ---
  duration_ms: 0.177
  ...
```

**Comment by pmq20** [comment]
```
not ok 93 parallel/test-child-process-spawnsync
#
# assert.js:85
#   throw new assert.AssertionError({
#   ^
# AssertionError: exit status should be zero
#     at Object.<anonymous> (C:\c\vendor\node-v7.0.0\test\parallel\test-child-process-spawnsync.js:10:8)
#     at Module._compile (module.js:638:32)
#     at Object.Module._extensions..js (module.js:647:10)
#     at Module.load (module.js:555:32)
#     at tryModuleLoad (module.js:508:12)
#     at Function.Module._load (module.js:500:3)
#     at Module.runMain (module.js:672:10)
#     at run (bootstrap_node.js:389:7)
#     at startup (bootstrap_node.js:144:9)
#     at bootstrap_node.js:530:3
  ---
  duration_ms: 0.189
  ...
```

**Comment by pmq20** [comment]
```
not ok 95 parallel/test-child-process-spawnsync-input
#
# assert.js:85
#   throw new assert.AssertionError({
#   ^
# AssertionError: null === 0
#     at checkSpawnSyncRet (C:\c\vendor\node-v7.0.0\test\parallel\test-child-process-spawnsync-input.js:24:10)
#     at Object.<anonymous> (C:\c\vendor\node-v7.0.0\test\parallel\test-child-process-spawnsync-input.js:69:1)
#     at Module._compile (module.js:638:32)
#     at Object.Module._extensions..js (module.js:647:10)
#     at Module.load (module.js:555:32)
#     at tryModuleLoad (module.js:508:12)
#     at Function.Module._load (module.js:500:3)
#     at Module.runMain (module.js:672:10)
#     at run (bootstrap_node.js:389:7)
#     at startup (bootstrap_node.js:144:9)
  ---
  duration_ms: 0.770
  ...
```

**Comment by pmq20** [comment]
```
not ok 432 parallel/test-http-chunk-problem
# events.js:160
#       throw er; // Unhandled 'error' event
#       ^
#
# Error: spawn cat ENOENT
#     at exports._errnoException (util.js:1026:11)
#     at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
#     at onErrorNT (internal/child_process.js:359:16)
#     at _combinedTickCallback (internal/process/next_tick.js:74:11)
#     at process._tickCallback (internal/process/next_tick.js:98:9)
  ---
  duration_ms: 0.527
  ...
```

**Comment by pmq20** [comment]
```
not ok 741 parallel/test-pipe-head
# C:\c\vendor\node-v7.0.0\test\parallel\test-pipe-head.js:14
#   if (err) throw err;
#            ^
#
# Error: Command failed: "C:\c\vendor\node-v7.0.0\Release\node.exe" "C:\c\vendor\node-v7.0.0\test\fixtures\print-10-lines.js" | head -2
# 'head' is not recognized as an internal or external command,
# operable program or batch file.
#
#     at ChildProcess.exithandler (child_process.js:210:12)
#     at emitTwo (events.js:106:13)
#     at ChildProcess.emit (events.js:191:7)
#     at maybeClose (internal/child_process.js:877:16)
#     at Socket.<anonymous> (internal/child_process.js:334:11)
#     at emitOne (events.js:96:13)
#     at Socket.emit (events.js:188:7)
#     at Pipe._handle.close [as _onclose] (net.js:501:12)
  ---
  duration_ms: 0.164
  ...
```

**Comment by pmq20** [comment]
```
not ok 765 parallel/test-process-kill-null
# internal/process.js:156
#       throw new TypeError('invalid pid');
#       ^
#
# TypeError: invalid pid
#     at process.kill (internal/process.js:156:13)
#     at Object.<anonymous> (C:\c\vendor\node-v7.0.0\test\parallel\test-process-kill-null.js:9:19)
#     at Module._compile (module.js:638:32)
#     at Object.Module._extensions..js (module.js:647:10)
#     at Module.load (module.js:555:32)
#     at tryModuleLoad (module.js:508:12)
#     at Function.Module._load (module.js:500:3)
#     at Module.runMain (module.js:672:10)
#     at run (bootstrap_node.js:389:7)
#     at startup (bootstrap_node.js:144:9)
  ---
  duration_ms: 0.170
  ...
```

**Comment by ChristopherFry** [comment]
Hi Minqi, I'm seeing the same issues that you were on Windows 10 Professional as well.  Any tips or suggestions on how to resolve these?  Thanks!
